name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!  

      - name: create python file
        run: python generate.py    

      # Copy the existing profile.csv file to the dist directory
      - name: Copy profile.csv to dist
        run: cp profile.csv dist/
      
      # Add steps to create JSON file, run unit tests, etc.
      - name: Create JSON file
        run: |
          echo '[{"name": "John", "age": 30},{"name": "Jane", "age": 25}]' > data.json

      - name: Copy to dist
        run: |
          mkdir dist
          cp data.json dist/data.json
          cp index.html dist/index.html
          cp script.js dist/script.js
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
       
