name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!      

      - name: Create CSV file
        run: |
          echo "Name, Age" > profiles.csv
          cat data.txt >> profiles.csv
      
      # Add steps to create JSON file, run unit tests, etc.
      - name: Create JSON file
        run: |
          echo '[{"name": "John", "age": 30},{"name": "Jane", "age": 25}]' > data.json
      
      - name: Run unit tests
        run: python calculateTests.py
          # Command to run unit tests goes here

      - name: Copy to dist
        run: |
          mkdir dist
          cp index.html dist/index.html
          cp data.json dist/data.json
          cp script.js dist/script.js
          cp profiles.csv dist/profiles.csv
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
       


